Azure/aks-engine-azurestack

- OWNERS
Removing `azure/aks-engine` approvers from OWNERS.
> chore: make jadarsie the sole approver

- .pipelines/vhd-builder.yaml
- packer.mk
- vhd/packer/init-variables.sh
Adding an extra step to the Linux VHD pipeline so it publishes the new VHD as a SIG image version. 
This is meant to speed up validation for #19. A SIG image can be used as the cluster nodes OS as indicated [here](https://github.com/Azure/aks-engine-azurestack/blob/v0.71.0/docs/topics/features.md#feat-shared-image-gallery) 
**Notes**:
> ci: Linux VHD pipeline creates SIG image version

- parts/k8s/cloud-init/artifacts/cse_install.sh
- pkg/engine/templates_generated.go
Upgrading `runc` to v1.1.4 as this particular version is available in `packages.microsoft.com` for both UbuntuServer 18.04 and 20.04.
> chore: upgrade runc to v1.1.4

- .pipelines/e2e-job-template.yaml
- .pipelines/pr-e2e.yaml
- .pipelines/vhd-builder.yaml
- vhd/packer/init-variables.sh
- vhd/packer/vhd-image-builder.json
Tweaking the Linux VHD pipeline so it can build VHDs based on Ubuntu Server 18.04 OR 20.04.
> ci: Linux VHD pipeline supports Ubuntu 20.04

- parts/k8s/cloud-init/artifacts/cse_main.sh
- pkg/api/defaults-sysctld.go
- pkg/engine/templates_generated.go
Fix an issue where multi-master clusters provision fails if distro is set to `ubuntu-18` or `ubuntu-20.04`, and network plugin is set to `azure`.
Cloud-init network configuration does not set eth0's address to the NIC's primary address. This breaks the etcd cluster as the cluster members do not trust requests from unexpected sources.
> fix: ensure eth0 addr is set to NIC's primary addr

- vhd/packer/configure-windows-vhd.ps1
Fix syntax error in Windows VHD script
> fix: syntax error in Windows VHD script

- .pipelines/e2e-job-template.yaml
- .pipelines/e2e-step-template.yaml
- .pipelines/pr-e2e.yaml
- examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
- examples/e2e-tests/kubernetes/release/default/definition.json
- examples/e2e-tests/userassignedidentity/vmas/kubernetes-vmas-multimaster.json
- examples/e2e-tests/userassignedidentity/vmas/kubernetes-vmas.json
- examples/e2e-tests/userassignedidentity/vmss/kubernetes-vmss.json
The E2E PR check only validate non-MSI cluster definitions as MSI is not supported on ASH.
**Notes**:
> ci: e2e PR check does not use MSI

- .pipelines/pr-e2e.yaml
The E2E PR check only validate AvailabilitySet node pools as VMSS is not supported on ASH.
**Notes**:
> ci: e2e PR check does not use custom VNET

- examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
- examples/e2e-tests/kubernetes/release/default/definition.json
- examples/e2e-tests/kubernetes/windows/hybrid/definition.json
- examples/e2e-tests/kubernetes/zones/definition.json
- examples/e2e-tests/userassignedidentity/vmss/kubernetes-vmss.json
The E2E PR checks only validate VMAS cluster definitions as VMSS is not supported on ASH.
**Notes**:
> ci: e2e PR check does not use AvailabilitySets

- parts/k8s/addons/azure-cloud-provider.yaml
- pkg/engine/templates_generated.go
It seems that the default value of `fsGroupPolicy` of `CSIDriver` resources (`ReadWriteOnceWithFSType`) requires storage classes to explicitly define their `fsType` to successfully modify PV permissions when required.
This PR explicitly set `fsType` to its default `ext4`. 
Related to #67
**Notes**:
> chore: set fsType to ext4 in supported storage classes

- parts/k8s/addons/coredns.yaml
- pkg/engine/templates_generated.go
Changing the CoreDNS addon manager mode from `EnsureExist` to `Reconcile`.
The cluster upgrade process produces the correct addon spec (/etc/kubernetes/addons/coredns.yaml) but the new spec is not applied until the CoreDNS deployment is kubectl-deleted. The `Reconcile` addon manager mode will fix this inconvenient.
The custom `Corefile` configmap keeps the `EnsureExist` mode so cluster upgrades do not erase user-provided overrides.
Related to #66
**Notes**:
> fix: CoreDNS image not updated after cluster upgrade

- parts/k8s/cloud-init/artifacts/cse_install.sh
- parts/k8s/cloud-init/artifacts/cse_main.sh
- pkg/engine/templates_generated.go
- vhd/packer/install-dependencies.sh
The `apache2-utils` package is no longer required.
**Notes**:
> chore: remove package apache2-utils from VHD

- examples/azure-stack/kubernetes-azurestack.json
kubernetes-azurestack.json uses distro aks-ubuntu-20.04 instead of aks-ubuntu-18.04
> fix: kubernetes-azurestack.json uses distro aks-ubuntu-20.04

- docs/topics/azure-stack.md
- examples/azure-stack/migratepv.sh
Update documentation to reflect that azurestack-csi-driver addon is enabled for mixed clusters, since release 0.75.3.
**Notes**:
> docs: Enable azurestack-csi-driver addon for mixed clusters

- parts/k8s/cloud-init/artifacts/cse_config.sh
- pkg/engine/templates_generated.go
- test/e2e/kubernetes/kubernetes_test.go
The bootstrap script only ensures that at least 1 addon-manager is up and running. This PR makes sure all expected instances are up and running.
Test "should have core kube-system componentry running" checks if all the expected pods are present AND running, instead of just validating if the present pods are running. Adding extra validation because addon-manager to catch regressions.
> bug: enforce each addon manager pod

- pkg/api/k8s_versions.go
- vhd/packer/install-dependencies.sh
https://github.com/coredns/coredns/releases/tag/v1.9.4
> chore: upgrade coredns to v1.9.4

- .github/workflows/create-release-branch.yaml
- Makefile
- scripts/gh-create-release-branch.sh
New security polices block creating PRs from a GH action. Updating the `create-release-branch` workflow so it only creates the changelog commit.
Added script to run the workflow through GH CLI:
```
RELEASE_VERSION=v0.76.0 RELEASE_FROM_BRANCH=master make create-release-branch
```
**Notes**:
> ci: gen-release-changelog wf creates branch and commit

- .github/workflows/release.yaml
- Makefile
- docs/community/release-checklist.md
> ci: release workflow tags the correct commit

- test/e2e/kubernetes/scripts/stig-validate.sh
- test/e2e/kubernetes/scripts/ubuntu-installed-packages-validate.sh
Previously, the test "should validate installed software packages" was failing because auditd was expected, but could not be found. This fix removes auditd as an expected package for all clusters.
Instead, now the stig validation test itself will verify auditd is installed, since auditd is only need for stig compliant clusters.
**Notes**:
> test: remove auditd from packages validate script

- pkg/api/k8s_versions.go
- vhd/packer/install-dependencies.sh
Previously, for air-gapped clusters on k8s v1.25, kube-addon-manager would be stuck on ImagePullBackOff because it could not download the specified MCR 9.1.6 image. The VHD only contains 9.1.5.
This PR adds 9.1.6 to the VHD. Also, changes the GCR kube-addon-manager image to 9.1.6.
**Notes**:
> fix: add kube-addon-manager v9.1.6 to vhd

- .github/workflows/create-release-branch.yaml
- .github/workflows/test-vhd-no-egress.yaml
Update the create-release-branch Github action to call the new test-vhd-no-egress Github action. With this change, the create-release-branch Github action will first run full test suites on the current k8s versions, with no outbound connection. If passed, then it will create the release branch and changelog PR.
See example run create-release-branch: https://github.com/christinalau0/aks-engine-azurestack/actions/runs/4494630778/jobs/7907894274
See example run test-vhd-no-egress: https://github.com/christinalau0/aks-engine-azurestack/actions/runs/4494961470/jobs/7908080869 …
> ci: call test-vhd-no-egress github workflow from create-release-branch

- parts/k8s/cloud-init/artifacts/cse_config.sh
- parts/k8s/cloud-init/artifacts/cse_customcloud.sh
- pkg/engine/templates_generated.go
- test/e2e/engine/template.go
- test/e2e/kubernetes/kubernetes_test.go
Previously, deploying mixed clusters (linux + windows nodes) with azuredisk-csi-driver addon hit custom data too long error: 
`Custom data in OSProfile must be in Base64 encoding and with a maximum length of 87380 characters.`
- This PR shortens variable names in cloud init scripts, reducing custom data length. 
- ci: Test suites previously set EnableTelemetry to true by default, which caused the CSE to be longer. This PR sets EnableTelemetry to false by default.
- ci: Fix featureflag nil pointers now that the EnableTelemetry feature flag is no longer set by default. …
> fix: shorten custom data in cloud init files

- Makefile
- test/e2e/Makefile
Go version was bumped from 1.17 to 1.19. As a result, e2e tests in cluster.sh run into this error:
```
fatal: detected dubious ownership in repository at '/aks-engine-azurestack'
To add an exception for this directory, call:
 git config --global --add safe.directory /aks-engine-azurestack
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
This VCS behavior was introduced in go 1.18:
> The go command now embeds version control information in binaries. It includes the currently checked-out revision, commit time, and a flag indicating whether edited or untracked files are present. Version control information is embedded if the go command is invoked in a directory within a Git, Mercurial, Fossil, or Bazaar repository, and …
> ci: exclude version control information from binary

- pkg/api/converterfromapi.go
- pkg/api/converterfromapi_test.go
- pkg/api/convertertoapi.go
- pkg/api/convertertoapi_test.go
`linuxProfile.enableUnattendedUpgrades` is not honored nor persisted in the output API Model.
By default, `enableUnattendedUpgrades` is set to `true`. In practice, this bug affected those users that set the value to `false`. In that case, the `false` value was ignored and unattended upgrades were not disabled.
This fix should effectively disable unattended upgrades for those customers that would like to disable it (air-gapped environments most likely).
Fixes #44
> fix: enableUnattendedUpgrades not honored

- cmd/addpool.go
Adding multiple Windows node pools using `aks-engine-azurestack addpool` results in conflicting VM names. This fix ensure that the VM name prefixes differ.
Fixes #136
> fix: addpool generates prefixes based on pool count

- pkg/api/const.go
- pkg/api/defaults.go
`runUnattendedUpgradesOnBootstrap` is persisted in the output API Model only if a value is set explicitly.
This PR ensures that `runUnattendedUpgradesOnBootstrap` is always persisted.
The default behavior is not altered.
**Notes**:
> fix: persist runUnattendedUpgradesOnBootstrap even if not set by input API model

- parts/k8s/addons/ip-masq-agent.yaml
- pkg/engine/templates_generated.go
Apply recommended [security context](https://github.com/kubernetes-sigs/ip-masq-agent/blob/v2.8.0/ip-masq-agent.yaml#L19-L22) for the ip-masq-agent addon
> chore: update ip-masq-agent security context

- .github/workflows/codeql.yml
For now this runs on a schedule. Eventually it will be added as a PR gate.
Example: https://github.com/jadarsie/aks-engine-azurestack/actions/runs/5258626232/jobs/9503097760
> security: run CodeQL daily as a GH action

- pkg/engine/virtualmachines.go
- pkg/engine/virtualmachinescalesets.go
Fix 2 instances of `codeql` warning `"Incorrect conversion between integer types"`.
Fixes #146
> security: incorrect conversion between integer types

- parts/k8s/addons/azure-network-policy.yaml
- pkg/api/k8s_versions.go
- pkg/engine/templates_generated.go
- vhd/packer/install-dependencies.sh
https://github.com/Azure/azure-container-networking/releases/tag/v1.4.32
With this version upgrade of azure network policy manager component, pods can now establish egress network connections when they are in a state of terminating (During the default 30 second grace period).
**Notes**:
> chore: upgrade azure network policy manager to v1.4.32

- cmd/get_logs.go
- scripts/collect-windows-logs.ps1
- test/e2e/cluster.sh
Removing docker logs from the Windows log collection script.
Fixes #150
> fix: stop collecting docker engine logs for Windows nodes

- scripts/collect-windows-logs.ps1
Fixes collected windows logs zip file being empty.
Previously windows logs were empty because the collect-windows-logs script would not complete, erroring at the Compress-Archive progress bar.
**Notes**:
> fix: disable powershell progress bar during ssh to collect windows logs

- pkg/api/defaults.go
During upgrade and scale commands, WindowsContainerdURL was not being updated. With this change, updating WindowsContainerdURL will follow the same pattern as updating containerd version. 
Fixes upgrade and scale when WindowsContainerdURL has changed.
**Notes**:
> fix: update WindowsContainerdURL during upgrade and scale

- examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
- examples/no_outbound.json
- pkg/api/addons_test.go
- pkg/api/const.go
- pkg/engine/networksecuritygroups.go
- pkg/engine/networksecuritygroups_test.go
- test/e2e/kubernetes/kubernetes_test.go
- test/e2e/kubernetes/workloads/pod-pvc.yaml
- vhd/packer/install-dependencies.sh
- Set useCloudControllerManager=true in disconnected api model
- Allow access to arm service tag in nsg for disconnected scenario
- Disable azure file csi driver addon
- Add nginx image to vhd for pvc test in disconnected
**Notes**:
> ci: use cloud controller manager in disconnected pipeline

- pkg/api/const.go
- vhd/packer/configure-windows-vhd.ps1
Also adding extra images to simplify the transition to use HostProcesses instead of `csi-proxy`:
- `mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v1.10.0-windows-hp` 
- `mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v1.26.5-windows-hp`
**Notes**:
> chore: upgrade Windows csi-proxy to v1.1.3

- test/e2e/kubernetes/kubernetes_test.go
- test/e2e/kubernetes/pod/pod.go
- test/e2e/kubernetes/workloads/windows-hostprocess.yaml
- vhd/packer/configure-windows-vhd.ps1
Adding a e2e test to validate Windows HostProcess pods.
**Notes**:
> test: e2e validates Windows HostProcess pods

- parts/k8s/cloud-init/artifacts/cse_customcloud.sh
- pkg/engine/templates_generated.go
keep MTU to 1500 for CNI kubenet
**Notes**:
> chore: set MTU to 1500 for the kubenet CNI

- examples/addons/cluster-autoscaler/README.md
> docs: clarify cluster-autoscaler support on Azure Stack Hub

- cmd/rotatecerts/arm.go
- docs/topics/rotate-certs.md
- docs/tutorials/cli-overview.md
- pkg/helpers/ssh/init.go
- pkg/helpers/ssh/init_darwin.go
- pkg/helpers/ssh/init_linux.go
- pkg/helpers/ssh/init_windows.go
- pkg/helpers/ssh/ssh.go
Modify the behavior of the rotate-certs command so it does not add new entries to the `known_hosts` file. Instead, new entries are added to a copy of the file (`~/.aks-engine-azurestack/known_hosts`). 
Related: #149
> chore: rotate-certs creates its own known_hosts copy

- pkg/api/defaults-apiserver.go
- pkg/api/defaults-apiserver_test.go
- pkg/api/defaults-cloud-controller-manager.go
- pkg/api/defaults-cloud-controller-manager_test.go
- pkg/api/defaults-controller-manager.go
- pkg/api/defaults-controller-manager_test.go
- pkg/api/defaults-kubelet.go
- pkg/api/defaults-kubelet_test.go
- pkg/api/defaults-scheduler.go
- pkg/api/defaults-scheduler_test.go
- pkg/api/defaults.go
- pkg/api/vlabs/validate_test.go
- In Kubernetes v1.28, several flags and feature gates were removed.
Users with existing api-models containing such a flag or feature gate would get broken deployments and upgrades. This PR will automatically remove the flag even if the user specifies it, for k8s v1.28+.
- Added proper unit tests for all removed flags and feature gates.
| Feature gates | PR |
|----------|----------|
| AdvancedAuditing | [kubernetes/kubernetes#118763](https://github.com/kubernetes/kubernetes/pull/118763)|
| CSIMigrationGCE   | [kubernetes/kubernetes#117055](https://github.com/kubernetes/kubernetes/pull/117055)|
| CSIStorageCapacity    | [kubernetes/kubernetes#118018](https://github.com/kubernetes/kubernetes/pull/118018)|
| DelegateFSGroupToCSIDriver    | …
> chore: remove invalid k8s v1.28 flags and feature gates

- .github/policies/branch-protection.yml
This PR adds Branch Protection policies for this repo. The branch protection yaml file was created to match our existing branch policies with Github's built in mechanism. However, it additionally adds some extra rules (requireLastPushApproval, requiredApprovingReviewsCount) for SDL minimum requirements.
**Notes**:
> security: Add branch protection (Github Policy Service)

- test/e2e/config/config.go
- test/e2e/kubernetes/kubernetes_test.go
- test/e2e/kubernetes/service/service.go
- test/e2e/runner.go
This PR adds new parameters to the E2E test framework, `SkipAzLogin` and `CheckIngressIPOnly`. By default, they are set to false, so that no changes are needed to our Hub test suites. 
**Notes**:
> ci: Add SkipAzLogin and CheckIngressIPOnly parameters

- .github/workflows/release.yaml
- vhd/packer/configure-windows-vhd-phase2.ps1
- vhd/packer/install-dependencies.sh
- vhd/packer/write-release-notes-windows.ps1
- This is a temporary mitigation to get VHD release notes and cgmanifest.json during AIB VHD pipeline. 
- Note that when the image builder resource group is created, it must be manually locked so that the AIB customization.log and storage account will not be deleted by AIB pipeline after successful image creation. 
- In the future, we should add a proper step to copy out the VHD release notes and cgmanifest.json.
- Removed validation steps in release.yaml, these steps should be done by ADO pipelines (test vhd no egress and PR E2E) before triggering release.yaml. …
> ci: Output AIB release notes and cgmanifest to customization.log 

- .devcontainer.json
- .github/workflows/nightly-build.yaml
- Makefile
- hack/tools/Makefile
- makedev.ps1
- test/e2e/cluster.sh
The go-dev base image was archived, its last update was for go 1.21: https://github.com/deis/docker-go-dev/blob/v1.39.1/rootfs/Dockerfile
This PR removes the use of go-dev base image, and instead uses the MAR go base image: https://mcr.microsoft.com/en-us/artifact/mar/oss/go/microsoft/golang/tags
In addition, this PR adds make targets to install azure cli, kubectl, k, azcopy, etc. The steps now are to use the MAR go base image, and then run `make bootstrap`.
**Notes**:
> ci: Replace go-dev base image

- vhd/aib/AKSeImageTemplateWindows.json
- vhd/packer/configure-windows-vhd-phase2.ps1
- vhd/packer/sysprep-phase1.ps1
- vhd/packer/sysprep-phase2.ps1
Hub requires a fixed version of guest agent. When building the VHD, the Azure VM's guest agent must be removed before running sysprep, so that the created VM on Hub can run the windows CSE.
**Notes**:
> fix: remove guest agent before sysprep to run windows cse on hub

- parts/k8s/windowsinstallopensshfunc.ps1
- pkg/engine/templates_generated.go
- vhd/packer/configure-windows-vhd-phase1.ps1
- vhd/packer/configure-windows-vhd.ps1
Since AKS Engine v0.81.1, we could not ssh into windows agent nodes. This PR fixes the issue. 
The root cause is the Windows server 2019 base image (since Oct 2024). Installing openssh server causes issues when the openssh client is installed and patched - due to the new way windows handles features. The solution is to remove the open ssh client before installing the open ssh server. 
Additionally this PR updates the ssh install script to address CVEs. This matches upstream AgentBaker's latest updates: https://github.com/Azure/AgentBaker/blob/master/vhdbuilder/packer/windows/configure-windows-vhd.ps1#L527
If "Yes," did you notify that project's maintainers and …
> fix: Fix ssh for windows nodes

- parts/k8s/kuberneteswindowsfunctions.ps1
- parts/k8s/kuberneteswindowssetup.ps1
- pkg/engine/templates_generated.go
- vhd/packer/configure-windows-vhd-phase2.ps1
- vhd/packer/configure-windows-vhd.ps1
Remove telemetry code in Windows CSE code since we never use it
**Notes**:
> chore: Remove telemetry code in Windows CSE
