parts/k8s/cloud-init/artifacts/cis.sh, parts/k8s/cloud-init/artifacts/cse_config.sh, parts/k8s/cloud-init/artifacts/cse_helpers.sh, parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/cloud-init/artifacts/cse_main.sh, parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/api/azenvtypes.go, pkg/api/const.go, pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go, pkg/api/defaults.go, pkg/api/types.go, pkg/api/vlabs/const.go, pkg/api/vlabs/types.go, pkg/armhelpers/support_validator.go, pkg/engine/templates_generated.go, test/e2e/kubernetes/scripts/sshd-config-validate.sh, test/e2e/kubernetes/scripts/time-sync-validate.sh, test/e2e/kubernetes/scripts/ubuntu-installed-packages-validate.sh, vhd/packer/install-dependencies.sh
Add support to create Ubuntu20.04-based nodes. 
Fixes #19
=> feat: support UbuntuServer 20.04 nodes

scripts/ensure-generated.sh, scripts/validate-copyright-header.sh, test/e2e/cleanup.sh, test/e2e/kubernetes/scripts/vmss-health-check.sh, vhd/packer/vhd-rg-cleanup.sh
Fixed linting errors found by `shellcheck`.
=> ci: fixed ShellCheck errors

parts/k8s/cloud-init/artifacts/cse_config.sh, pkg/engine/templates_generated.go, vhd/packer/install-dependencies.sh
Removing unnecessary images from VHD cache.
=> chore: remove docker registry image from VHD

cmd/get_locations.go, cmd/get_locations_test.go, cmd/get_skus_test.go, pkg/api/vlabs/validate_test.go, pkg/operations/k8sapi_ops_test.go
=> bug: fixed broken UTs after linter upgrade

.github/workflows/pr.yaml
=> chore: execute pull request workflow on master branch

.github/workflows/create-release-branch.yaml, .github/workflows/large-cluster-test.yaml, .github/workflows/nightly-build.yaml, .github/workflows/release.yaml, .github/workflows/test-cluster-config.yaml, Makefile, cmd/root.go, cmd/rotatecerts/operations.go, cmd/upgrade.go, docs/community/developer-guide.md, docs/community/e2e-output-example.log, docs/topics/creating_new_clusters.md, docs/topics/rotate-certs.md, docs/topics/scale.md, docs/topics/upgrade.md, docs/tutorials/cli-overview.md, examples/addpool/addpool.sh, parts/k8s/kuberneteswindowssetup.ps1, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go, pkg/engine/templates_generated.go, test/e2e/cluster.sh, test/e2e/engine/cli.go, test/e2e/runner/cli_provisioner.go
Renamed binary from `aks-engine` to `aks-engine-azurestack`.
=> build: rename binary to aks-engine-azurestack

.github/workflows/pr.yaml, examples/no_outbound.json
Executing e2e as part of the PR checks on master
=> chore: added e2e to PR workflow

examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json, examples/e2e-tests/kubernetes/release/default/definition.json, examples/e2e-tests/kubernetes/zones/definition.json
AvailabilitySet clusters do not support AvailabilityZones
**Notes**:
=> fix: unit test checking e2e configs

.pipelines/pr-e2e.yaml
=> Update pr-e2e.yaml for Azure Pipelines

.pipelines/e2e-job-template.yaml, .pipelines/e2e-step-template.yaml
=> ci: e2e PR check sets tenant

.pipelines/e2e-job-template.yaml, .pipelines/e2e-step-template.yaml, .pipelines/pr-e2e.yaml
=> ci: fix variable name in e2e PR check

.pipelines/e2e-job-template.yaml, .pipelines/pr-e2e.yaml, examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json, examples/e2e-tests/kubernetes/release/default/definition.json, examples/e2e-tests/userassignedidentity/vmas/kubernetes-vmas-multimaster.json, examples/e2e-tests/userassignedidentity/vmas/kubernetes-vmas.json, examples/e2e-tests/userassignedidentity/vmss/kubernetes-vmss.json
=> ci: E2E PR check uses user assigned identity

.pipelines/e2e-job-template.yaml, .pipelines/pr-e2e.yaml, pkg/api/azenvtypes.go, pkg/api/common/versions.go, vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh
=> ci: PR checks consume SIG images

.pipelines/e2e-job-template.yaml, .pipelines/pr-e2e.yaml
=> ci: PR gate runs E2E suite

vhd/packer/vhd-image-builder.json
change reference of cni config to scripts dir
Missed this additional change in the previous PR https://github.com/Azure/aks-engine-azurestack/commit/45995691d539c2990b52a3bf19251d7af4a91361
**Notes**:
=> fix: change reference of cni config to scripts dir

vhd/packer/windows-2019-vars.json
Updating Windows VHD packer job to use Jan 2023 patches
**Notes**:
=> chore: Update Windows VHD packer job to use Jan 2023 patches

pkg/api/azenvtypes.go, vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-azurestack-ctrd-17763.3887.20230332.txt, vhd/release-notes/aks-windows/2019-datacenter-core-azurestack-smalldisk-17763.3887.20230332.txt
update default windows image to jan 2023
include release notes
**Notes**:
=> chore: update default windows image to jan 2023

.github/workflows/create-release-branch.yaml
We are currently validating air-gapped on ASH instances, but having this validation as a fail-fast mechanism would be nice. 
Related to #78
**Notes**:
=> ci: remove no-egress job from create branch action

scripts/get-akse.sh
**Notes**:
Fixing typo in the get-akse script
=> fix: get-akse.sh pulls using the correct file name

.github/workflows/create-release-branch.yaml, .github/workflows/release.yaml, examples/no_outbound.json
=> ci: release workflows run no-egress scenarios

.choco/aks-engine-azurestack/aks-engine-azurestack.nuspec, .choco/aks-engine-azurestack/tools/LICENSE.txt, .choco/aks-engine-azurestack/tools/chocolateyinstall.ps1, .choco/aks-engine-azurestack/update.ps1, .github/workflows/chocolatey.yaml
=> ci: chocolatey workflow

parts/k8s/kubernetesparams.t, pkg/api/const.go, pkg/api/defaults_test.go, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go, pkg/engine/templates_generated.go, vhd/packer/install-dependencies.sh
https://github.com/containerd/containerd/releases/tag/v1.5.16
**Notes**:
=> chore: upgrade containerd to 1.5.16

releases/CHANGELOG-v0.75.4.md
Add CHANGELOG for upcoming v0.75.4 release
=> release: v0.75.4 CHANGELOG 

pkg/api/common/versions.go, vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh
=> feat: add support for Kubernetes v1.24.11

.github/workflows/chocolatey.yaml, .github/workflows/create-release-branch.yaml, .github/workflows/generate-azure-consts.yaml, .github/workflows/large-cluster-test.yaml, .github/workflows/nightly-build.yaml, .github/workflows/release.yaml, .github/workflows/test-cluster-config.yaml, .github/workflows/update-go-mod-vendor.yaml
=> ci: update actions/checkout to v3

Makefile, test/e2e/Makefile
Previous PR https://github.com/Azure/aks-engine-azurestack/pull/121 forgot to change the "make build-binary" command.
**Notes**:
=> ci: exclude version control information from test binary

.github/workflows/create-release-branch.yaml, .github/workflows/release.yaml, .github/workflows/test-vhd-no-egress.yaml
- Removes the call to test-vhd-no-egress in create-release-branch Github action
- Adds the call to test-vhd-no-egress in release Github action
- Bumps release Github action to test k8s v1.24 + v1.25
- Example run: https://github.com/christinalau0/aks-engine-azurestack/actions/runs/4602072731
- Set cleanup if fail for test-vhd-no-egress github action
**Notes**:
=> ci: call test-vhd-no-egress from release github workflow

scripts/collect-logs.sh
=> feat: get-logs collects etcd metrics

vhd/packer/windows-2019-vars.json
=> chore: Update Windows VHD packer job to use Apr 2023 patches

releases/CHANGELOG-v0.76.0.md
=> release: v0.76.0 CHANGELOG

test/e2e/kubernetes/kubernetes_test.go, vhd/packer/install-dependencies.sh
Make sure that the E2E suite uses the busybox image pre-pulled from MCR
=> test: E2E suite pulls busybox from MCR

pkg/api/vlabs/validate.go
=> chore: remove private preview warning for AzureCNI

vhd/packer/install-dependencies.sh, vhd/packer/vhd-image-builder.json
Produce the component governance file containing installed apt packages as part of the VHD build process.
**Notes**:
=> build: produce cgmanifest.json per UbuntuVHD build

docs/topics/rotate-certs.md
Older AKS Engine releases (before v0.65.0) create a front-proxy PKI that expires after 2 years (730 days).
Added docs to explain how to deal with expired front-proxy certs
=> docs: how to renew front-proxy certs

parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/kubernetesparams.t, pkg/api/const.go, pkg/api/defaults_test.go, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go, pkg/engine/templates_generated.go, vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh
- https://github.com/containerd/containerd/releases/tag/v1.6.21
- https://launchpad.net/ubuntu/+source/runc/1.1.7-0ubuntu1
- The recommended runc version for containerd v1.6.21: https://github.com/containerd/containerd/blob/v1.6.21/script/setup/runc-version
**Notes**:
=> chore: upgrade containerd to v1.6.21 and runc to v1.1.7

vhd/packer/windows-2019-vars.json
Updating Windows VHD packer job to use July 2023 patches
**Notes**:
=> chore: Update Windows VHD packer job to use July 2023 patches

docs/topics/rotate-certs.md
=> docs: how to rotate spn credentials

releases/CHANGELOG-v0.77.0.md
release: v0.77.0 CHANGELOG
**Notes**:
=> release: v0.77.0 CHANGELOG

vhd/packer/windows-2019-vars.json
=> chore: include Windows Server August 2023 patches

parts/k8s/cloud-init/artifacts/cse_config.sh, parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/cse.go, pkg/engine/templates_generated.go
Remove unused docker0 bridge network when the container runtime is containerd
**Notes**:
=> fix: remove unused bridge network interface

releases/CHANGELOG-v0.78.0.md
=> release: v0.78.0 CHANGELOG

releases/CHANGELOG-v0.78.0.md
=> release: v0.78.0 CHANGELOG (#184)

.github/workflows/release.yaml
=> Skip HPC test

pkg/api/common/versions.go, vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh
=> chore: support Kubernetes v1.26.9

vhd/packer/windows-2019-vars.json
=> chore: include Windows Server October 2023 patches

releases/CHANGELOG-v0.79.0.md
=> release: v0.79.0 CHANGELOG

scripts/get-akse.sh
=> fix: script "get-akse.sh" uses the "aks-engine-azurestack" binary to determine installed version

vhd/packer/windows-2019-vars.json
=> chore: include Windows Server December 2023 patches

pkg/api/defaults-kubelet.go
…and agent profile.
chore: remove unsupported feature gates for kubelet config in master and agent profile
**Notes**:
=> chore: remove unsupported feature gates for kubelet config in master and agent profile

releases/CHANGELOG-v0.80.0.md
=> release: v0.80.0 CHANGELOG

releases/CHANGELOG-v0.80.1.md
release: v0.80.1 CHANGELOG
**Notes**:
=> release: v0.80.1 CHANGELOG

releases/CHANGELOG-v0.80.1.md
* release: v0.80.1 CHANGELOG
---------
Co-authored-by: GitHub Actions Bot <>
**Notes**:
=> release: v0.80.1 CHANGELOG (#226)

.github/workflows/create-release-branch.yaml
=> chore: grant write permission for create-release-branch workflow

releases/CHANGELOG-v0.80.2.md
release: v0.80.2 CHANGELOG
**Notes**:
=> release: v0.80.2 CHANGELOG

.github/workflows/generate-azure-consts.yaml, .github/workflows/release.yaml, .github/workflows/update-go-mod-vendor.yaml
=> chore: grant github action bot proper write permission

.github/policies/advanced-security.yml, .github/policies/branch-protection.yml
This PR adds advanced security policies for this repo. With Github's built in mechanism, secret scanning and secret scanning push protection is already enabled. The new yaml matches the current policy. 
Additionally, the new yaml enables pull request validation of dependencies. When this feature is enabled, a PR check is automatically run on every PR to determine whether the PR has added or modified any dependencies. If it has, those dependencies are checked for vulnerabilities. If vulnerabilities are found, then the severity of the dependency is compared against the failOnSeverity setting to determine if the check should fail.
If "Yes," did you notify that …
=> security: Add advanced security policy (Github Policy Service)

cmd/root.go
Fix go lint in previous PR.
**Notes**:
=> chore: remove usage of module autorest/azure, golint fix

hack/tools/Makefile, pkg/api/common/versions.go, vhd/packer/configure-windows-vhd-phase2.ps1, vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh
- support Kubernetes v1.28.15 & v1.29.10
- kubectl's latest versions are no longer released at storage.googleapis.com. Instead, it is recommended to use dl.k8s.io, see [issue](https://github.com/kubernetes/kubernetes/issues/127796) for more information.
**Notes**:
=> chore: support Kubernetes v1.28.15 & v1.29.10

vhd/aib/AKSeImageTemplateWindows.json, vhd/packer/windows-2019-vars.json
Updating Windows VHD AIB job to use Oct 2024 patches
**Notes**:
=> chore: Update Windows VHD AIB job to use Oct 2024 patches

hack/tools/Makefile, test/e2e/cluster.sh
This PR fixes Hub E2E tests so that Azure CLI can get access to the cert, in the E2E test DVM.
**Notes**:
=> ci: fix Hub E2E tests azcli cert

pkg/armhelpers/compute.go
After move to new compute api version, still need to specify instanceView to avoid nil pointer during rotate-certs.
**Notes**:
=> fix: specify instanceView to avoid nil pointer during rotate-certs

parts/k8s/addons/cloud-node-manager.yaml, pkg/engine/templates_generated.go
Cloud node manager v1.29 needs to be run as root in order to access /etc/kubernetes/certs. 
**Notes**:
=> fix: specify securityContext in cloud node manager

releases/CHANGELOG-v0.81.0.md
=> release: v0.81.0 CHANGELOG

.github/workflows/release.yaml, hack/tools/Makefile
=> ci: fix release github action

releases/CHANGELOG-v0.81.0.md
=> release: Update v0.81.0 CHANGELOG

pkg/engine/armtype.go, pkg/engine/deployment.go, pkg/engine/deployment_test.go, pkg/engine/vmextensions_test.go
Specifying feature flag enableTelemetry: True would cause the ARM template deployment to fail. This PR bumps the api version and removes the DeploymentARMResource alias to fix the issue. 
**Notes**:
=> fix: Fix enableTelemetry apiVersion and ARM template

releases/CHANGELOG-v0.81.1.md
=> release: v0.81.1 CHANGELOG

.github/workflows/codeql.yml
CodeQL v2 will be deprecated 12/5/24: https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
**Notes**:
=> ci: update CodeQL action v3

parts/k8s/cloud-init/artifacts/cse_config.sh, pkg/engine/templates_generated.go
=> fix: Update Chrony Service Config (#288)

releases/CHANGELOG-v0.80.3.md
=> release: v0.80.3 CHANGELOG

parts/k8s/cloud-init/artifacts/cse_stig_ubuntu2204.sh, pkg/api/azenvtypes.go, pkg/engine/template_generator_test.go, pkg/engine/templates_generated.go, test/e2e/kubernetes/kubernetes_test.go
=> security: Update ubuntu 22.04 stig config

vhd/aib/AKSeImageTemplateWindows.json, vhd/packer/windows-2019-vars.json
=> chore: Update Windows Base Image version for March 2025

parts/k8s/addons/azure-network-policy.yaml, parts/k8s/addons/kube-proxy.yaml, pkg/api/azenvtypes.go, pkg/api/const.go, pkg/api/k8s_versions.go, pkg/engine/templates_generated.go, vhd/packer/configure-windows-vhd-phase2.ps1, vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh
=> chore: update Azure CNI version to v1.4.59

vhd/aib/AKSeImageTemplateWindows.json, vhd/packer/configure-windows-vhd-phase1.ps1, vhd/packer/configure-windows-vhd-phase2.ps1
=> ci: Azure image builder template to download Windows signed scripts

examples/azure-stack/kubernetes-azurestack.json, examples/azure-stack/kubernetes-windows.json, pkg/api/common/versions.go, vhd/packer/configure-windows-vhd-phase2.ps1, vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh
=> chore: Support k8s 1.29.15

releases/CHANGELOG-v0.82.0.md
=> release: v0.82.0 CHANGELOG

releases/CHANGELOG-v0.82.1.md
=> release: v0.82.1 CHANGELOG

docs/tutorials/quickstart.md
Remove sensitive information from doc for security purpose
**Notes**:
=> doc: Update quickstart doc

vhd/aib/AKSeImageTemplateWindows.json, vhd/packer/configure-windows-vhd-phase2.ps1, vhd/packer/install-dependencies.sh
Security fixes for Ubuntu and Windows Base Images:
- Remove traceroute package for Ubuntu (https://ubuntu.com/security/notices/USN-6478-1)
- Update Windows Server 2019 base image to include Windows security patches (https://support.microsoft.com/en-us/topic/windows-server-images-for-june-2025-97701859-0dbb-4ec9-a6f0-f06e0fc47fac#id0ebbbbd=2019)
- Add registry keys to disable TLS 1.0 and 1.1
**Notes**:
=> security: security fixes for Ubuntu and Windows Base Images

test/e2e/cluster.sh
=> fix: fix incorrect decoding in e2e log

pkg/engine/const.go, pkg/engine/template_generator.go, vhd/aib/AKSeImageTemplateWindows.json
=> chore: move windows ps files from cse to vhd

vhd/aib/AKSeImageTemplateWindows.json
=> chore: update Windows OS image version

vhd/aib/AKSeImageTemplateLinux.json, vhd/aib/AKSeImageTemplateWindows.json
=> fix: Remove Vnet Config for Image Builder Service for S360
